hibernate.connection.driver_class=org.postgresql.Driver
hibernate.connection.url=jdbc:postgresql://localhost:5432/doccollab
hibernate.connection.username=user
hibernate.connection.password=password
hibernate.dialect=org.hibernate.dialect.PostgreSQL10Dialect
hibernate.hbm2ddl.auto=update
hibernate.show_sql=true
hibernate.hikari.connectionTimeout=20000
hibernate.hikari.minimumIdle=10
hibernate.hikari.maximumPoolSize=20
hibernate.hikari.idleTimeout=300000
